[green_agent]
agentbeats_id = "019b4d06-1da3-7c22-88fa-f4660061a779"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = "019b4d08-d84c-7a00-b2ec-4905ef7afc96"
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
# Add your assessment config here
domain = "airline"
num_tasks = 3
